// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://oqxwhdjusvtwudtlsnpa.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9xeHdoZGp1c3Z0d3VkdGxzbnBhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTEwMzAzMTUsImV4cCI6MjA2NjYwNjMxNX0.0TphAFbY0uQgCAb5r4Cn_Ac6OToVvIEktwwVyS4MfCQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);